name: Deploy to Azure

on:  
  push:
    branches:
      - master
env:
  # basic  
  resourceGroup: kikundi_backend_container
  location: eastus
  
  acrName: kikundi.azurecr

jobs:  
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup java 11
      uses: actions/setup-java@v2
      with:
         java-version: 11
         distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build --scan

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Building a composed image
      run: docker-compose up -d

    - name: Pushing the image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kikundi_backend:latest
